#!/usr/bin/env python
'''
Created on 27.06.2012

@author: gschoenb
@version: 1.1
'''
import argparse
import logging
import sys

from fio.FioJob import FioJob
from perfTest.DeviceTest import DeviceTest
from perfTest.PerfTest import SsdPerfTest
from perfTest.PerfTest import HddPerfTest
import perfTest.PerfTest as pT
import plots.compPlots as pcp

if __name__ == '__main__':
    vTest = FioJob()
    fioVersion = vTest.__str__()#Fetch the fio version
    tkPerfVersion = "TKperf Version: " + pT.__version__
    tkPerfVersion += " using " + fioVersion
    parser = argparse.ArgumentParser()

    parser.add_argument("mode", help="specify the test mode for the device", choices=["hdd","ssd"])
    parser.add_argument("xmls", help="XML files to read from", type=str, nargs='+')

    parser.add_argument("-v","--version", help="get the version information", action='version',version=tkPerfVersion)
    parser.add_argument("-d","--debug", help="get detailed debug information",action ='store_true')
    parser.add_argument("-q","--quiet", help="turn off logging of info messages",action ='store_true')

    args = parser.parse_args()
    if args.debug == True:
        logging.basicConfig(filename='tkperf-cmp.log',level=logging.DEBUG)
    if args.quiet == True:
        logging.basicConfig(filename='tkperf-cmp.log',level=logging.WARNING)
    else:
        logging.basicConfig(filename='tkperf-cmp.log',level=logging.INFO)

    #strip the filename suffix as it is appended automatically
    for i,file in enumerate(args.xmls):
        if file.endswith('.xml'):
            file = file[:-4]
        args.xmls[i] = file

    toCompare = []
    for file in args.xmls:
        if args.mode == "ssd":
            myTest = SsdPerfTest(file, 'none', 0, 0)
        if args.mode == "hdd":
            myTest = HddPerfTest(file, 'none', 0, 0)
        myTest.fromXml()
        toCompare.append(myTest)

    pcp.compWriteSatIOPSPlt(toCompare)
    pcp.compILPlt(toCompare,'IOPS')
    pcp.compILPlt(toCompare,'LAT')
    pcp.compTPPlt(toCompare)
    exit(0)